### ISSUE TITLE
Nextcloud Integration

### ISSUE THREAD

**Issue by jcharaoui** [derikb/character-sheet-5e#53]
For those of us chilly to proprietary online services (eg. Dropbox), support for saving to [Nextcloud](https://nextcloud.org/) (most likely via WebDAV) would be nice.

**Comment by baldurmen** [comment]
This sounds slightly more complicated than just dropping the Dropbox JS picker though...

From what I've seen, [this](https://github.com/perry-mitchell/webdav-fs) is what Nextcloud [seems to recommend](https://nextcloud.com/blog/using-webdav-fs-to-access-files-in-nextcloud/).

**Comment by derikb** [comment]
The main reason I put the dropbox option in there (besides that I actually use dropbox) is that it can be done without a server side component. I really want to keep this whole thing static.

**Comment by derikb** [comment]
Also closing this since it doesn't seem to be a static file/web thing.
