### ISSUE TITLE
Historical Citation and Comparison with other repos

### ISSUE THREAD

**Issue by DonaldTsang** [derikb/character-sheet-5e#78]
It seems that there is a repo https://github.com/theoperatore/character that does something but is not active.
Would it be a good idea to give it a mention, or even do a comparison in feautres?

Hard flex mode: mention (or even borrow code from, since GPLv3) https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet

**Comment by derikb** [comment]
I don't particularly have an interest in doing that.

It's not clear what features that first one has (the install instructions are more than I want to go through to look), and the later seems all about building pdfs, which... avoiding fill-in pdfs was part of why I started this project because in my experience they always work really bad on my Mac.

**Comment by DonaldTsang** [comment]
@derikb to redefine things, the former should be noted in the documentation, and the latter could be a means to boost features for the project using purely the internal JS and not the PDF, or if that is not possible, at least note some feature differences in the documentation.

**Comment by derikb** [comment]
Why _should_ I mention other projects I've never heard of?

And if you want to make feature requests based on the other app feel free to. Right now I just add features as they come up for my own needs, but I'll entertain others if they seem helpful and doable without adding in a whole server layer.

**Comment by DonaldTsang** [comment]
> adding in a whole server layer
I think the JS code can work without a network, and that such a feature is only used for "updates" and "extras"?
If not then it is not a good idea to ask straight away.

**Comment by derikb** [comment]
Yes the js can... but I'm saying that depends on what specific features are requested.

**Comment by BrandonKMLee** [comment]
From the perspective of an MPMB user, the MPMB is a container and downloader for D&D content that is formatted specifically for programming purposes, and that included everything from class, race, background, item, and spell data, and also other data. The PDF form is merely one type of UI frontend for the data to be held in JS in the back of the PDF.

**Comment by derikb** [comment]
Closing this, as there isn't anything actionable and specific in here.
