### ISSUE TITLE
missing config/firebase.js

### ISSUE THREAD

**Issue by SimonDeRidder** [derikb/character-sheet-5e#90]
`npm run start` and `npm run build` fail with:
```
✘ [ERROR] Could not resolve "../config/firebase.js"

    src/services/firebaseService.js:2:19:
      2 │ import config from '../config/firebase.js';
        ╵                    ~~~~~~~~~~~~~~~~~~~~~~~

1 error
```

**Comment by derikb** [comment]
Yeah. If you want to run your own instance you'll need to use your own firebase setup.

I should probably put that in the docs.

If you don't want to use it, you should just be able to put a file that exports empty object there... I'll retest that.

**Comment by derikb** [comment]
Oh, looks like I neglected to handle that part (really though I had). Will add some error catching if the config is empty.

**Comment by derikb** [comment]
Ok @SimonDeRidder I added an empty config to the repo, updated so it handles the possibility of empty, and then made sure the "Sign in" button only shows if you have the configuration set. So it should work as before (no signin/remote) direct from the dist/ folder. But if you _want_ remote you can add your own configs to ./src/config/firebase.js and then `npm run build`

**Comment by SimonDeRidder** [comment]
Awesome, thanks!
